export const REQUEST_PRODUCTS_PENDING = 'REQUEST_PRODUCTS_PENDING';
export const REQUEST_PRODUCTS_SUCCESS = 'REQUEST_PRODUCTS_SUCCESS';
export const REQUEST_PRODUCTS_FAIL = 'REQUEST_PRODUCTS_FAIL';

export const REQUEST_PRODUCT_DETAILS_PENDING =
  'REQUEST_PRODUCT_DETAILS_PENDING';
export const REQUEST_PRODUCT_DETAILS_SUCCESS =
  'REQUEST_PRODUCT_DETAILS_SUCCESS';
export const REQUEST_PRODUCT_DETAILS_FAIL = 'REQUEST_PRODUCT_DETAILS_FAIL';
